name: Generate Matrix Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate-matrix-snake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate Snake Matrix Style
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: lucasramon
          outputs: |
            dist/github-contribution-grid-snake.svg
          snake_color: '#39ff14'                # matrix green snake
          background_color: '#000000'           # total black background
          grid_color: '#111111'                 # very dark dots
          color_snake: '#39ff14'
          color_dots: '#0f0,#0c0,#090,#060,#030' # matrix green levels

      - name: Push SVG to output branch
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git fetch origin output
          git switch output || git checkout -b output
          cp dist/github-contribution-grid-snake.svg .
          git add github-contribution-grid-snake.svg
          git commit -m "update matrix style snake svg" || echo "No changes"
          git push origin output
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
